---
# title: "#**Joint mechanistic modeling of viral and antibody responses to vaccines in NHPs**\n"
# author: "Marie Alexandre"
# date: "`r Sys.Date()`"
output:
  md_document:
    variant: markdown_github
---



# **Joint mechanistic modeling of viral and antibody responses to vaccines in NHPs**
Author: Marie Alexandre  
Date: `r Sys.Date()`


## **Brief description of the project**

**Objective:** The modeling work presented in this project is an original work whose purpose is to develop a mechanistic model jointly describing *viral and antibody dynamics* in non-human primates (NHPs) in order to quantify the minimum concentration of neutralizing antibodies, identified as relevant mechanistic correlate of protection (mCoP), considered as *protective against viral infection spreading* early after infection.


**Data:** The proposed model was estimated on viral, binding and neutralizing antibody dynamics collected longitudinally in naive and convalescent NHPs, vaccinated or not, involved in a preclinical study evaluating the efficacy of next-generation protein-based vaccines developed by the French Vaccine Research Institute (VRI). We focused our interest in the early phase following the Delta SARS-CoV-2 infection, with data collected regularly up to 30 days post-infection.  
For each animal, the following data were collected: 1) viral genomic RNA (gRNA) and subgenomic RNA (sgRNA) quantified in nasopharyngeal and tracheal swabs by RT-qPCR,  2) Binding IgG against Delta RBD titrated using MSD immunoassay, 3) antibodies inhibiting binding of the RBD domain to the ACE2 receptor using the MSD pseudo-neutralization assay.  
Data used in this modeling have been published in an original research paper (currently under revision). 


**Method:** We *first* developed the original mechanistic model describing viral, binding and neutralizing antibody dynamics, and their mutual interactions, on the basis of our previous modeling work aiming at modeling post-infection viral dynamics and identifying mCoP (see Folder *"ViralDyn_mCoPIdentification"*), and focusing exclusively our interest on the ability of neutralizing antibodies to reduce viral infectivity.  
*Second*, we estimated the model on NHPs data, using SAEM algorithm implemented in Monolix software, and identified vaccine- and natural-induced immunity mechanisms impacting antibody dynamics.  
*Third*, we derived the concentration of neutralizing antibodies assumed as protective against Delta infection spreading, using the basic reproduction number (R0).  
*Finally*, we conducted counterfactual simulations to better understand and validate immune mechanisms driving immune control we identified. 



## **Description of folders**
The code provided in this folder is an original code developed in this modeling work currently under submission for publication. 


### **1) Simulated data** (folder *Simulated_data*)
This folder includes: 

 1.  **A dataset of simulated data**. This dataset has been directly simulated from our original dataset and used in the other files of the project to help users to understand our codes. It's therefore noted that results obtained here can be slightly different from those obtained with the original dataset.  
 2. **R code for descriptive analysis of observed data**. Original R code developed to perform descriptive analysis of viral and antibody dynamics (separately) and generate figures for publication.
 

### **2) Model Identifiability** (folder *Model_Identifiability_Julia*)

This folder includes:

1.  **Julia codes for identifiability analysis**. Original Julia codes (.jl files) developed to analysis the structural identifiability of the joint model and results obtained (.txt files). Results were obtained with Julia 1.11.3.


### **3) Model Estimation** (folder *Model_Estimation_Monolix*)
This folder includes: 

1. **Mlxtran codes for Monolix projects**. Original mlxtran codes (.txt files) of the two mechanistic models used to model our observed data: (1) the "Viral model" describing only viral dynamics, without including antibody responses, (2) the overall model jointly describing viral and antibody responses, and their mutual interactions.

2. **R codes for Monolix Estimation of mechanistic models**. Original R codes developed to create and estimate Monolix projects of the final version of the "Viral model" and the "Joint model". Codes have been initially developed for Monolix2023R1. 

3. **Final Monolix Projects**. Final version of Monolix Projects selected to describe our data and ready for publication.

4. **R codes and mlxtran codes for Monolix results analysis**. Original R code developed to generate/analysis and visualize model results after Monolix estimation.


### **4) Counterfactual scenarios simulation** (folder *Counterfactual_Scenario_Simulx*)
This folder includes:

1. **Mlxtran codes for simulx simulation**. Original codes (txt files) used by Simulx to simulate Joint model dynamics according to counterfactual statements. 

2. **R code for counterfactual simulations**. Original R code developed to run counterfactual statements using Simulx and visualize results. 
















